# These config values will be shared by all environments but can be overridden.
common: &common
  client_id: "event_driven_app"

development:
  <<: *common
  brokers:
    - localhost:9092

test:
  <<: *common
  brokers:
    - localhost:9092

production:
  <<: *common
  brokers:
    - kafka1.event_driven_app.com:9092
    - kafka2.event_driven_app.com:9092
    - kafka3.event_driven_app.com:9092
